### ISSUE TITLE
Using mavenCentral() instead of jcenter()

### ISSUE THREAD

**Issue by antoniokranjcina** [NickM-27/LinkPreview#38]
Hi,

Will this library be usable without using `jcenter()` but `mavenCentral()`.

**Comment by NickM-27** [comment]
Hi, I would like to, just need to get it set up at some point

**Comment by antoniokranjcina** [comment]
Do you have any ideas when should that be possible?

**Comment by NickM-27** [comment]
I'm very busy right now so I can't say for sure, whenever I'm able to get to it

**Comment by NickM-27** [comment]
Okay the library is now published in mavenCentral under `com.nicknackdevelopment:linkpreview:4.0`
